version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8100:9000"
    volumes:
      - ./modulingg:/usr/src/app/modulingg
      - ./modules:/usr/src/app/modules
    command: python modulingg/main.py
